### ISSUE TITLE
Windows 8 - nondeterministic error - database overlaps and filter auto-hides

### ISSUE THREAD

**Issue by xstreck1** [sybila/Esther#1]
Way to reproduce the error:

1) Input and save the lysogenic.dbm model from DiscreteModels.
2) Call Parsybone
3) Open the produced .sqlite database (happens only from time to time)
4) Database is duplicated right below the BehaviourMap button. Filter hides instantly after appearing.
![Capture](https://f.cloud.github.com/assets/758604/213488/3ba93102-838a-11e2-8433-3cb8a694b071.PNG)

**Comment by GeorgeKolcak** [comment]
Fixed in commit 2217c7eb20 (2013-03-05) by implementation of tabs.
